name: pickup_delivery_app
description: Pick Up & Delivery Management System
publish_to: 'none'
version: 4.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.3.0
  shared_preferences: ^2.5.4
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_file: ^3.5.11
  pdf: ^3.11.3
  path: ^1.9.1
  uuid: ^4.1.0
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  dio: ^5.3.3
  version: ^3.0.2
  url_launcher: ^6.3.2
  flutter_downloader: ^1.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"